/**
 * SolarGrid — On-Chain Game Client
 * Connects to deployed BOLT ECS programs on Solana Devnet.
 * Uses @magicblock-labs/bolt-sdk for world/entity/component/system interactions.
 */

import { Connection, PublicKey, Transaction } from "@solana/web3.js";
import { Buffer } from "buffer";
import { AnchorProvider, Program, BN, Idl } from "@coral-xyz/anchor";
import {
  InitializeNewWorld,
  AddEntity,
  InitializeComponent,
  ApplySystem,
  getComponentPda,
} from "@magicblock-labs/bolt-sdk";

import {
  COMPONENT_PLANET_ID,
  COMPONENT_RESOURCES_ID,
  COMPONENT_FLEET_ID,
  SYSTEM_BUILD_ID,
  SYSTEM_PRODUCE_ID,
  SYSTEM_SHIPYARD_ID,
  SYSTEM_LAUNCH_ID,
  SYSTEM_ATTACK_ID,
  WORLD_PROGRAM_ID,
} from "../constants";

// ── IDLs (generated by anchor build) ─────────────────────────────────────────
// These are imported at runtime from the build output
// For now we define the minimal IDL structure needed to fetch accounts

const PLANET_IDL: Idl = {
  address: COMPONENT_PLANET_ID.toBase58(),
  metadata: { name: "planet", version: "0.1.0", spec: "0.1.0" },
  instructions: [],
  accounts: [{ name: "Planet", discriminator: [242,27,236,42,220,217,132,128] }],
  types: [{
    name: "Planet",
    type: {
      kind: "struct" as const,
      fields: [
        { name: "owner",                type: "pubkey" },
        { name: "name",                 type: { array: ["u8", 32] } },
        { name: "galaxy",               type: "u16" },
        { name: "system",               type: "u16" },
        { name: "position",             type: "u8" },
        { name: "diameter",             type: "u32" },
        { name: "temperature",          type: "i16" },
        { name: "maxFields",            type: "u16" },
        { name: "usedFields",           type: "u16" },
        { name: "metalMine",            type: "u8" },
        { name: "crystalMine",          type: "u8" },
        { name: "deuteriumSynthesizer", type: "u8" },
        { name: "solarPlant",           type: "u8" },
        { name: "fusionReactor",        type: "u8" },
        { name: "roboticsFactory",      type: "u8" },
        { name: "naniteFactory",        type: "u8" },
        { name: "shipyard",             type: "u8" },
        { name: "metalStorage",         type: "u8" },
        { name: "crystalStorage",       type: "u8" },
        { name: "deuteriumTank",        type: "u8" },
        { name: "researchLab",          type: "u8" },
        { name: "missileSilo",          type: "u8" },
        { name: "buildQueueItem",       type: "u8" },
        { name: "buildQueueTarget",     type: "u8" },
        { name: "buildFinishTs",        type: "i64" },
        { name: "boltMetadata",         type: { defined: { name: "BoltMetadata" } } },
      ],
    },
  }, {
    name: "BoltMetadata",
    type: { kind: "struct" as const, fields: [{ name: "authority", type: "pubkey" }] },
  }],
} as unknown as Idl;

const RESOURCES_IDL: Idl = {
  address: COMPONENT_RESOURCES_ID.toBase58(),
  metadata: { name: "resources", version: "0.1.0", spec: "0.1.0" },
  instructions: [],
  accounts: [{ name: "Resources", discriminator: [0,0,0,0,0,0,0,0] }],
  types: [{
    name: "Resources",
    type: {
      kind: "struct" as const,
      fields: [
        { name: "metal",            type: "u64" },
        { name: "crystal",          type: "u64" },
        { name: "deuterium",        type: "u64" },
        { name: "metalHour",        type: "u64" },
        { name: "crystalHour",      type: "u64" },
        { name: "deuteriumHour",    type: "u64" },
        { name: "energyProduction", type: "u64" },
        { name: "energyConsumption",type: "u64" },
        { name: "metalCap",         type: "u64" },
        { name: "crystalCap",       type: "u64" },
        { name: "deuteriumCap",     type: "u64" },
        { name: "lastUpdateTs",     type: "i64" },
        { name: "boltMetadata",     type: { defined: { name: "BoltMetadata" } } },
      ],
    },
  }, {
    name: "BoltMetadata",
    type: { kind: "struct" as const, fields: [{ name: "authority", type: "pubkey" }] },
  }],
} as unknown as Idl;

const FLEET_IDL: Idl = {
  address: COMPONENT_FLEET_ID.toBase58(),
  metadata: { name: "fleet", version: "0.1.0", spec: "0.1.0" },
  instructions: [],
  accounts: [{ name: "Fleet", discriminator: [109,207,251,48,106,2,136,163] }],
  types: [{
    name: "Fleet",
    type: {
      kind: "struct" as const,
      fields: [
        { name: "smallCargo",      type: "u32" },
        { name: "largeCargo",      type: "u32" },
        { name: "lightFighter",    type: "u32" },
        { name: "heavyFighter",    type: "u32" },
        { name: "cruiser",         type: "u32" },
        { name: "battleship",      type: "u32" },
        { name: "battlecruiser",   type: "u32" },
        { name: "bomber",          type: "u32" },
        { name: "destroyer",       type: "u32" },
        { name: "deathstar",       type: "u32" },
        { name: "recycler",        type: "u32" },
        { name: "espionageProbe",  type: "u32" },
        { name: "colonyShip",      type: "u32" },
        { name: "solarSatellite",  type: "u32" },
        { name: "activeMissions",  type: "u8" },
        { name: "missions",        type: { array: [{ defined: { name: "Mission" } }, 4] } },
        { name: "boltMetadata",    type: { defined: { name: "BoltMetadata" } } },
      ],
    },
  }, {
    name: "Mission",
    type: {
      kind: "struct" as const,
      fields: [
        { name: "missionType",     type: "u8" },
        { name: "destination",     type: "pubkey" },
        { name: "departTs",        type: "i64" },
        { name: "arriveTs",        type: "i64" },
        { name: "returnTs",        type: "i64" },
        { name: "sSmallCargo",     type: "u32" },
        { name: "sLargeCargo",     type: "u32" },
        { name: "sLightFighter",   type: "u32" },
        { name: "sHeavyFighter",   type: "u32" },
        { name: "sCruiser",        type: "u32" },
        { name: "sBattleship",     type: "u32" },
        { name: "sBattlecruiser",  type: "u32" },
        { name: "sBomber",         type: "u32" },
        { name: "sDestroyer",      type: "u32" },
        { name: "sDeathstar",      type: "u32" },
        { name: "sRecycler",       type: "u32" },
        { name: "sEspionageProbe", type: "u32" },
        { name: "sColonyShip",     type: "u32" },
        { name: "cargoMetal",      type: "u64" },
        { name: "cargoCrystal",    type: "u64" },
        { name: "cargoDeuterium",  type: "u64" },
        { name: "applied",         type: "bool" },
      ],
    },
  }, {
    name: "BoltMetadata",
    type: { kind: "struct" as const, fields: [{ name: "authority", type: "pubkey" }] },
  }],
} as unknown as Idl;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface OnChainPlanet {
  owner: PublicKey;
  name: string;
  galaxy: number;
  system: number;
  position: number;
  diameter: number;
  temperature: number;
  maxFields: number;
  usedFields: number;
  metalMine: number;
  crystalMine: number;
  deuteriumSynthesizer: number;
  solarPlant: number;
  fusionReactor: number;
  roboticsFactory: number;
  naniteFactory: number;
  shipyard: number;
  metalStorage: number;
  crystalStorage: number;
  deuteriumTank: number;
  researchLab: number;
  missileSilo: number;
  buildQueueItem: number;
  buildQueueTarget: number;
  buildFinishTs: number;
}

export interface OnChainResources {
  metal: number;
  crystal: number;
  deuterium: number;
  metalHour: number;
  crystalHour: number;
  deuteriumHour: number;
  energyProduction: number;
  energyConsumption: number;
  metalCap: number;
  crystalCap: number;
  deuteriumCap: number;
  lastUpdateTs: number;
}

export interface OnChainMission {
  missionType: number;
  destination: string;
  departTs: number;
  arriveTs: number;
  returnTs: number;
  ships: {
    sSmallCargo: number; sLargeCargo: number; sLightFighter: number;
    sHeavyFighter: number; sCruiser: number; sBattleship: number;
    sBattlecruiser: number; sBomber: number; sDestroyer: number;
    sDeathstar: number; sRecycler: number; sEspionageProbe: number; sColonyShip: number;
  };
  cargoMetal: number;
  cargoCrystal: number;
  cargoDeuterium: number;
  applied: boolean;
}

export interface OnChainFleet {
  smallCargo: number; largeCargo: number; lightFighter: number;
  heavyFighter: number; cruiser: number; battleship: number;
  battlecruiser: number; bomber: number; destroyer: number;
  deathstar: number; recycler: number; espionageProbe: number;
  colonyShip: number; solarSatellite: number;
  activeMissions: number;
  missions: OnChainMission[];
}

export interface GameAddresses {
  worldPda: PublicKey;
  entityPda: PublicKey;
  planetPda: PublicKey;
  resourcesPda: PublicKey;
  fleetPda: PublicKey;
}

// ── SolarGrid Client ──────────────────────────────────────────────────────────

export class SolarGridClient {
  private connection: Connection;
  private provider: AnchorProvider;
  private planetProgram: Program;
  private resourcesProgram: Program;
  private fleetProgram: Program;

  constructor(connection: Connection, provider: AnchorProvider) {
    this.connection = connection;
    this.provider = provider;
    this.planetProgram    = new Program(PLANET_IDL,    provider);
    this.resourcesProgram = new Program(RESOURCES_IDL, provider);
    this.fleetProgram     = new Program(FLEET_IDL,     provider);
  }

  private storageKey(owner: PublicKey): string {
    return `solargrid_addresses_${owner.toBase58()}`;
  }

  // ── Setup ──────────────────────────────────────────────────────────────────

  async initializeWorld(): Promise<GameAddresses> {
    const payer = this.provider.wallet.publicKey;

    // 1. Create world
    const { transaction: wTx, worldPda } = await InitializeNewWorld({
      payer, connection: this.connection,
    });
    await this.provider.sendAndConfirm(wTx);

    // 2. Create planet entity
    const { transaction: eTx, entityPda } = await AddEntity({
      payer, world: worldPda, connection: this.connection,
    });
    await this.provider.sendAndConfirm(eTx);

    // 3. Attach components
    const { transaction: pTx, componentPda: planetPda } = await InitializeComponent({
      payer, entity: entityPda, componentId: COMPONENT_PLANET_ID,
    });
    await this.provider.sendAndConfirm(pTx);

    const { transaction: rTx, componentPda: resourcesPda } = await InitializeComponent({
      payer, entity: entityPda, componentId: COMPONENT_RESOURCES_ID,
    });
    await this.provider.sendAndConfirm(rTx);

    const { transaction: fTx, componentPda: fleetPda } = await InitializeComponent({
      payer, entity: entityPda, componentId: COMPONENT_FLEET_ID,
    });
    await this.provider.sendAndConfirm(fTx);

    const addresses = { worldPda, entityPda, planetPda, resourcesPda, fleetPda };

    // Save to localStorage
    localStorage.setItem(this.storageKey(payer), JSON.stringify({
      worldPda:     worldPda.toBase58(),
      entityPda:    entityPda.toBase58(),
      planetPda:    planetPda.toBase58(),
      resourcesPda: resourcesPda.toBase58(),
      fleetPda:     fleetPda.toBase58(),
    }));

    return addresses;
  }

  loadAddresses(owner: PublicKey): GameAddresses | null {
    try {
      const saved = localStorage.getItem(this.storageKey(owner));
      if (!saved) return null;
      const parsed = JSON.parse(saved);
      return {
        worldPda:     new PublicKey(parsed.worldPda),
        entityPda:    new PublicKey(parsed.entityPda),
        planetPda:    new PublicKey(parsed.planetPda),
        resourcesPda: new PublicKey(parsed.resourcesPda),
        fleetPda:     new PublicKey(parsed.fleetPda),
      };
    } catch { return null; }
  }

  // ── Reads ──────────────────────────────────────────────────────────────────

  async fetchPlanet(planetPda: PublicKey): Promise<OnChainPlanet | null> {
    try {
      const raw = await this.planetProgram.account["planet"].fetch(planetPda) as any;
      return {
        owner:                 raw.owner as PublicKey,
        name:                  Buffer.from(raw.name).toString("utf8").replace(/\0/g, "") || "Homeworld",
        galaxy:                raw.galaxy,
        system:                raw.system,
        position:              raw.position,
        diameter:              raw.diameter || 12800,
        temperature:           raw.temperature || 32,
        maxFields:             raw.maxFields || 163,
        usedFields:            raw.usedFields || 0,
        metalMine:             raw.metalMine,
        crystalMine:           raw.crystalMine,
        deuteriumSynthesizer:  raw.deuteriumSynthesizer,
        solarPlant:            raw.solarPlant,
        fusionReactor:         raw.fusionReactor,
        roboticsFactory:       raw.roboticsFactory,
        naniteFactory:         raw.naniteFactory,
        shipyard:              raw.shipyard,
        metalStorage:          raw.metalStorage,
        crystalStorage:        raw.crystalStorage,
        deuteriumTank:         raw.deuteriumTank,
        researchLab:           raw.researchLab,
        missileSilo:           raw.missileSilo,
        buildQueueItem:        raw.buildQueueItem,
        buildQueueTarget:      raw.buildQueueTarget,
        buildFinishTs:         (raw.buildFinishTs as BN).toNumber(),
      };
    } catch (e) {
      console.error("fetchPlanet:", e);
      return null;
    }
  }

  async fetchResources(resourcesPda: PublicKey): Promise<OnChainResources | null> {
    try {
      const raw = await this.resourcesProgram.account["resources"].fetch(resourcesPda) as any;
      const bn = (v: any) => v instanceof BN ? v.toNumber() : Number(v);
      return {
        metal:             bn(raw.metal),
        crystal:           bn(raw.crystal),
        deuterium:         bn(raw.deuterium),
        metalHour:         bn(raw.metalHour),
        crystalHour:       bn(raw.crystalHour),
        deuteriumHour:     bn(raw.deuteriumHour),
        energyProduction:  bn(raw.energyProduction),
        energyConsumption: bn(raw.energyConsumption),
        metalCap:          bn(raw.metalCap),
        crystalCap:        bn(raw.crystalCap),
        deuteriumCap:      bn(raw.deuteriumCap),
        lastUpdateTs:      bn(raw.lastUpdateTs),
      };
    } catch (e) {
      console.error("fetchResources:", e);
      return null;
    }
  }

  async fetchFleet(fleetPda: PublicKey): Promise<OnChainFleet | null> {
    try {
      const raw = await this.fleetProgram.account["fleet"].fetch(fleetPda) as any;
      const bn = (v: any) => v instanceof BN ? v.toNumber() : Number(v);
      const missions: OnChainMission[] = (raw.missions || [])
        .filter((m: any) => m.missionType !== 0)
        .map((m: any) => ({
          missionType:    m.missionType,
          destination:    (m.destination as PublicKey).toBase58(),
          departTs:       bn(m.departTs),
          arriveTs:       bn(m.arriveTs),
          returnTs:       bn(m.returnTs),
          ships: {
            sSmallCargo:    m.sSmallCargo,    sLargeCargo:    m.sLargeCargo,
            sLightFighter:  m.sLightFighter,  sHeavyFighter:  m.sHeavyFighter,
            sCruiser:       m.sCruiser,       sBattleship:    m.sBattleship,
            sBattlecruiser: m.sBattlecruiser, sBomber:        m.sBomber,
            sDestroyer:     m.sDestroyer,     sDeathstar:     m.sDeathstar,
            sRecycler:      m.sRecycler,      sEspionageProbe:m.sEspionageProbe,
            sColonyShip:    m.sColonyShip,
          },
          cargoMetal:     bn(m.cargoMetal),
          cargoCrystal:   bn(m.cargoCrystal),
          cargoDeuterium: bn(m.cargoDeuterium),
          applied:        m.applied,
        }));
      return {
        smallCargo:     raw.smallCargo,    largeCargo:    raw.largeCargo,
        lightFighter:   raw.lightFighter,  heavyFighter:  raw.heavyFighter,
        cruiser:        raw.cruiser,       battleship:    raw.battleship,
        battlecruiser:  raw.battlecruiser, bomber:        raw.bomber,
        destroyer:      raw.destroyer,     deathstar:     raw.deathstar,
        recycler:       raw.recycler,      espionageProbe:raw.espionageProbe,
        colonyShip:     raw.colonyShip,    solarSatellite:raw.solarSatellite,
        activeMissions: raw.activeMissions,
        missions,
      };
    } catch (e) {
      console.error("fetchFleet:", e);
      return null;
    }
  }

  // ── Writes ─────────────────────────────────────────────────────────────────

  async startBuild(entityPda: PublicKey, buildingIdx: number): Promise<string> {
    const now = BigInt(Math.floor(Date.now() / 1000));
    const args = Buffer.alloc(10);
    args.writeUInt8(0, 0);
    args.writeUInt8(buildingIdx, 1);
    args.writeBigInt64LE(now, 2);

    const { transaction } = await ApplySystem({
      authority: this.provider.wallet.publicKey,
      systemId:  SYSTEM_BUILD_ID,
      entities: [{
        entity: entityPda,
        components: [
          { componentId: COMPONENT_PLANET_ID },
          { componentId: COMPONENT_RESOURCES_ID },
        ],
      }],
      args: Array.from(args),
    });
    return this.provider.sendAndConfirm(transaction);
  }

  async finishBuild(entityPda: PublicKey): Promise<string> {
    const now = BigInt(Math.floor(Date.now() / 1000));
    const args = Buffer.alloc(10);
    args.writeUInt8(1, 0);
    args.writeUInt8(0, 1);
    args.writeBigInt64LE(now, 2);

    const { transaction } = await ApplySystem({
      authority: this.provider.wallet.publicKey,
      systemId:  SYSTEM_BUILD_ID,
      entities: [{
        entity: entityPda,
        components: [
          { componentId: COMPONENT_PLANET_ID },
          { componentId: COMPONENT_RESOURCES_ID },
        ],
      }],
      args: Array.from(args),
    });
    return this.provider.sendAndConfirm(transaction);
  }

  async settleProduction(entityPda: PublicKey): Promise<string> {
    const now = BigInt(Math.floor(Date.now() / 1000));
    const args = Buffer.alloc(8);
    args.writeBigInt64LE(now, 0);

    const { transaction } = await ApplySystem({
      authority: this.provider.wallet.publicKey,
      systemId:  SYSTEM_PRODUCE_ID,
      entities: [{
        entity: entityPda,
        components: [{ componentId: COMPONENT_RESOURCES_ID }],
      }],
      args: Array.from(args),
    });
    return this.provider.sendAndConfirm(transaction);
  }

  async buildShip(entityPda: PublicKey, shipType: number, quantity: number): Promise<string> {
    const now = BigInt(Math.floor(Date.now() / 1000));
    const args = Buffer.alloc(10);
    args.writeUInt8(shipType, 0);
    args.writeUInt32LE(quantity, 1);
    args.writeBigInt64LE(now, 2);

    const { transaction } = await ApplySystem({
      authority: this.provider.wallet.publicKey,
      systemId:  SYSTEM_SHIPYARD_ID,
      entities: [{
        entity: entityPda,
        components: [
          { componentId: COMPONENT_FLEET_ID },
          { componentId: COMPONENT_RESOURCES_ID },
        ],
      }],
      args: Array.from(args),
    });
    return this.provider.sendAndConfirm(transaction);
  }

  async launchFleet(params: {
    entityPda:      PublicKey;
    destEntityPda:  PublicKey;
    missionType:    number;
    ships:          Record<string, number>;
    cargoMetal?:    number;
    cargoCrystal?:  number;
    cargoDeuterium?:number;
    speedFactor?:   number;
    flightSeconds:  number;
  }): Promise<string> {
    const { entityPda, missionType, ships, flightSeconds } = params;
    const speedFactor = params.speedFactor || 100;
    const now = BigInt(Math.floor(Date.now() / 1000));

    const args = Buffer.alloc(94);
    let o = 0;
    args.writeUInt8(missionType, o++);
    const shipOrder = ["lightFighter","heavyFighter","cruiser","battleship",
      "battlecruiser","bomber","destroyer","deathstar","smallCargo","largeCargo",
      "recycler","espionageProbe","colonyShip"];
    for (const k of shipOrder) {
      args.writeUInt32LE(ships[k] || 0, o); o += 4;
    }
    args.writeBigUInt64LE(BigInt(params.cargoMetal    || 0), o); o += 8;
    args.writeBigUInt64LE(BigInt(params.cargoCrystal  || 0), o); o += 8;
    args.writeBigUInt64LE(BigInt(params.cargoDeuterium|| 0), o); o += 8;
    args.writeUInt8(speedFactor, o++);
    args.writeBigInt64LE(now, o); o += 8;
    args.writeBigInt64LE(BigInt(flightSeconds), o);

    const { transaction } = await ApplySystem({
      authority: this.provider.wallet.publicKey,
      systemId:  SYSTEM_LAUNCH_ID,
      entities: [{
        entity: entityPda,
        components: [
          { componentId: COMPONENT_FLEET_ID },
          { componentId: COMPONENT_RESOURCES_ID },
        ],
      }],
      args: Array.from(args),
    });
    return this.provider.sendAndConfirm(transaction);
  }
}

// ── Utility functions ─────────────────────────────────────────────────────────

export function formatNum(n: number): string {
  if (n >= 1e9) return (n / 1e9).toFixed(2) + "B";
  if (n >= 1e6) return (n / 1e6).toFixed(2) + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1) + "K";
  return Math.floor(n).toLocaleString();
}

export function formatDuration(secs: number): string {
  secs = Math.max(0, Math.floor(secs));
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = secs % 60;
  return [h, m, s].map(v => String(v).padStart(2, "0")).join(":");
}

export function pendingProduction(res: OnChainResources, nowSec: number) {
  const dt = Math.max(0, nowSec - res.lastUpdateTs);
  return {
    metal:     Math.min(res.metal     + Math.floor(res.metalHour     * dt / 3600), res.metalCap),
    crystal:   Math.min(res.crystal   + Math.floor(res.crystalHour   * dt / 3600), res.crystalCap),
    deuterium: Math.min(res.deuterium + Math.floor(res.deuteriumHour * dt / 3600), res.deuteriumCap),
  };
}

export function buildCost(idx: number, currentLevel: number) {
  const bases: [number,number,number][] = [
    [60,15,0],[48,24,0],[225,75,0],[75,30,0],[900,360,900],
    [400,120,200],[1_000_000,500_000,100_000],[400,200,100],
    [1000,0,0],[1000,500,0],[1000,1000,0],[200,400,200],[20,20,0],
  ];
  const [bm,bc,bd] = bases[idx] || [0,0,0];
  const mult = Math.pow(1.5, currentLevel);
  return { m: Math.round(bm*mult), c: Math.round(bc*mult), d: Math.round(bd*mult) };
}

export function buildSeconds(idx: number, level: number, robotics: number): number {
  const { m, c } = buildCost(idx, level - 1);
  return Math.max(1, Math.floor((m + c) / (2500 * (1 + robotics))));
}

export function galaxyDistance(g1:number,s1:number,p1:number,g2:number,s2:number,p2:number) {
  if (g1 !== g2) return 20_000 + Math.abs(g1-g2)*40_000;
  if (s1 !== s2) return 2_700  + Math.abs(s1-s2)*95;
  return 1_000 + Math.abs(p1-p2)*1_000;
}

export function estimateFlightSeconds(distance:number, baseSpeed:number, speedFactor:number) {
  const speed = baseSpeed * speedFactor / 100;
  if (speed <= 0) return 86400;
  return Math.max(10, Math.floor((35_000/100) * Math.sqrt((10*distance)/speed) + 10));
}

export const SHIP_TYPES: Record<string, number> = {
  smallCargo:0, largeCargo:1, lightFighter:2, heavyFighter:3, cruiser:4,
  battleship:5, battlecruiser:6, bomber:7, destroyer:8, deathstar:9,
  recycler:10, espionageProbe:11, colonyShip:12, solarSatellite:13,
};
